### PR TITLE
Generate typespecs for postgres enum type

### PR DESCRIPTION
**Pull request by MortadaAK**
This will add `@type t` for the enum. 
For example, 
```elixir
defenum(TestEnum,:postgres_name,[:type_a,:type_b,:type_c])
```
will be expanded to 
```elixir
defmodule TextEnum do 
  @type t :: :type_a | :type_b | :type_c
end
```
There is a limitation of remote functions.

### CODE REVIEW

**Comment by gjaldon** [comment]
@MortadaAK could you add a test for this? Is it not possible to make it work with a remote function?

**Comment by slashmili** [comment]
I thought about adding test, it should be easy to add it using `Code.Typespec.fetch_specs/1`. However the problem is since `.exs` won't compile to beam files, this function can't load detail of a module that is defined in test files 😞

**Comment by bernardd** [comment]
Aw bother, I should have looked in the PRs- I just implemented the same thing myself. I did, however, come up with a half way decent way to test. I also implemented it for both the postgres and standard enum types. I'll open it in a new PR - please feel free to cherry pick any bits of mine in to this one, or vice versa.

**Comment by gjaldon** [comment]
Resolved in #84

**Pull request closed without merging**
