### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by AndrewDryga**

### CODE REVIEW

**Comment by gjaldon** [comment]
The branch that supports Ecto-2.0 has just been merged that it includes updates to mix deps.

**Comment by dmartingarcia** [comment]
Thanks @AndrewDryga @gjaldon 
could you upload 1.0 version to hex.pm?

**Comment by gjaldon** [comment]
@basestylo thanks for the reminder! It's now uploaded at https://hex.pm/packages/ecto_enum/1.0.0

**Comment by dmartingarcia** [comment]
@gjaldon I will be indebted to you! :clap:

**Comment by gjaldon** [comment]
No worries! :smile:

**Pull request closed without merging**
