### PR TITLE
Support string-backed enums

### PR DESCRIPTION
**Pull request by cesariouy**
These changes are useful for when a project is in the process of migrating to Postgres enums.

Huge shout-out to @mtwilliams for authoring issue #4 and PR #9! This borrows heavily from his work.

### CODE REVIEW

**Comment by cesariouy** [comment]
@gjaldon The failing build for Elixir 1.3.0 has to do with a Postgrex dependency issue (requires ~> 1.3.4 or ~> 1.4), which seems to be affecting other builds as well.

**Comment by cesariouy** [comment]
@gjaldon The tests are now passing, could you take a look at this?

**Comment by gjaldon** [comment]
@cesariouy I agree with the idea of string-backed enums for use in migrating. Will need to take more time to review though.

**Comment by archseer** [comment]
Sorry for the bump, but we'd find this feature useful for migrating from a legacy schema (string based field with preset values) as well.

**Comment by Freyskeyd** [comment]
thank's @gjaldon and @cesariouy for the work.

We also need these kind of changes to support string based Enum (for mysql).
Any idea of a release date?

**Comment by williamweckl** [comment]
Will this PR get merged?

**Comment by erikreedstrom** [comment]
@gjaldon What else do you require for us to get this merged in?

**Comment by mtwilliams** [comment]
FYI https://github.com/tsutsu/ecto_homoiconic_enum

**Comment by gjaldon** [comment]
This is stale since we already support string-backed enums after the rewrite

**Pull request closed without merging**
