### PR TITLE
Changes mix.exs to allow installation under a wider range of Ecto v2 versions

### PR DESCRIPTION
**Pull request by theangryangel**
Allows installation under >= 2.0.0 < 3.0.0.

### CODE REVIEW

**Comment by szabolcsmaj** [comment]
So when will this be merged?

**Comment by theangryangel** [comment]
If you need support *now*, you can use my branch directly in your mix.exs `{:ecto_enum, git: "https://github.com/theangryangel/ecto_enum.git", branch: "feat/ecto-2.1"}`. I promise I won't check in anything that breaks stuff 😄

**Comment by szabolcsmaj** [comment]
Thank you @theangryangel, I'll use your version till then :)

**Comment by ryanwinchester** [comment]
Have you guys got this working in the latest ecto/phoenix versions?

I get

    ** (ArgumentError) invalid or unknown type MyEnum for field :my_field

**Comment by theangryangel** [comment]
I have it working under Phoenix 1.3 with contexts. I can check the project mix lock file tomorrow, if you want specific version numbers

**Comment by theangryangel** [comment]
Looks like this was dealt with under another PR (#48)

I’ll keep my fork around just in case anyone’s using it.

**Comment by gjaldon** [comment]
Dep requirements are loosened in this commit https://github.com/gjaldon/ecto_enum/commit/4c936711b57fa49f863b0da3913567576eedeaac

**Pull request closed without merging**
